import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const PhaserGameNoSSR = dynamic(() => import("../components/game"), {
  ssr: false,
});
const PhaserGamePage: NextPage = () => <PhaserGameNoSSR />;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NextJs Phaser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PhaserGamePage />
      </main>
    </div>
  );
};

export default Home;
